// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzCFMsbcR9iE4GXFQ4rU5L8eL5ElAhW8',
    appId: '1:839028019846:web:d59b623413054372fd3707',
    messagingSenderId: '839028019846',
    projectId: 'instagram-clone-76edd',
    authDomain: 'instagram-clone-76edd.firebaseapp.com',
    storageBucket: 'instagram-clone-76edd.appspot.com',
    measurementId: 'G-0CQ6BSYM6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-v2xrzqg0AT7tzf4oAwYQWB7Gp8duqq8',
    appId: '1:839028019846:android:ebdfe07821f8037bfd3707',
    messagingSenderId: '839028019846',
    projectId: 'instagram-clone-76edd',
    storageBucket: 'instagram-clone-76edd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGe75NdAvClEBZlW1fxFN6KoBpMLy8No',
    appId: '1:839028019846:ios:7cb44537ab3f222ffd3707',
    messagingSenderId: '839028019846',
    projectId: 'instagram-clone-76edd',
    storageBucket: 'instagram-clone-76edd.appspot.com',
    iosBundleId: 'com.example.instanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEGe75NdAvClEBZlW1fxFN6KoBpMLy8No',
    appId: '1:839028019846:ios:4926de4d08b59a8afd3707',
    messagingSenderId: '839028019846',
    projectId: 'instagram-clone-76edd',
    storageBucket: 'instagram-clone-76edd.appspot.com',
    iosBundleId: 'com.example.instanet.RunnerTests',
  );
}
